### ISSUE TITLE
Not directly related, but where can I find more information about Pharo compiler plugin?

### ISSUE THREAD

**Issue by laike9m** [guillep/pharo-string-interpolation#1]
I didn't know this functionality exists until searching for "Smalltalk string interpolation" and found this repo. Would be interested to learn more about it. Thanks.

**Comment by guillep** [comment]
Hmm, I cannot tell if there is documentation somewhere. I can give you some pointers:
 - I think @StevenCostiou was working on documentation around the compiler.
 - @aranega was also interested on doing compiler extensions.
 - @MarcusDenker is the original designer/developer of the compiler.

Maybe you can get in contact with them? I'd also invite you to join us on discord (check http://pharo.org/community), we can continue the conversation there.

**Comment by laike9m** [comment]
cool, that would be great, thanks for help

Guille Polito <notifications@github.com> 于 2020年2月19日周三 上午12:43写道：
